### ISSUE TITLE
Make ingest job idempotent

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/sdr-api#424]
The current steps in the ingest job are:
1. Register an object and get back the druid.
2. Create the registration workflow.
3. Optionally, create the accession workflow.

However, things can go wrong between steps 1 and 2/3, resulting in objects like https://argo.stanford.edu/view/druid:rf229bh8033.

To make the ingest job idempotent:
1. When the druid is received from DSA and added to the background job result, the result should be saved immediately.
2. Register should only be performed if the background job result does not have a druid.

**Comment by jcoyne** [comment]
I still think there's a problem with this approach not being  idempotent if the database write fails.

**Comment by justinlittman** [comment]
@jcoyne and I looked at this and determined that the current implementation should be (relatively) idempotent and should handle retries appropriately.

The example we were looking at (https://argo.stanford.edu/view/druid:rf229bh8033) has been purged, so it is difficult to try to troubleshoot.

I'm going to close this ticket. @andrewjbtw if you encounter another (new) example of this, please let us know.

**Comment by andrewjbtw** [comment]
So I should have left the problem items around? Duplicate druid creation happened six times over the weekend.

**Comment by jcoyne** [comment]
I think the database constraint that we have in postgres will prevent duplicate druids. I don't think there is any other way to resolve that problem in our current architecture.

**Comment by andrewjbtw** [comment]
Right, my actual question that led to this ticket was: in the situation that currently leads to duplicate records with the same source id, what will happen when there's no Fedora and we can enforce uniqueness for source id? The situation(s) that lead that seem to be some issue with DSA that results in multiple attempts to create the same druid.

We could get:

- no druid created on the first attempt, retry succeeds
- druid created on first attempt with no workflow started, all retries fail because of source id conflict until someone intervenes
- something else

**Comment by jcoyne** [comment]
I think this script + the change to postgres will handle all of these possibilities. I don't think you can test this right now until we pull Fedora out of DSA entirely.
