### ISSUE TITLE
Implement user-based access controls so we can enable access for external users

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sdr-api#522]
In order to enable API access for external (non-SUL) users, the SDR-API should implement an access control scheme. The current API allows anyone with an account and password to modify any druid. Currently, only a small number of SUL users have accounts and the API operates as essentially an internal service.

While the scheme may grow over time in response to user needs and feedback, we could begin with the following set of permissions, modeled after the H2 permissions:

A non-(super)admin user should be able to

- Create new collections
- Create new items (in any collection? Ideally we'd be able to limit access to collections as we currently do in H2)
- Manage (update) only the collections or items that they "own", where "ownership" means
  - they created the collection/item and have retained ownership
  - ownership has been transferred to them (similar to how we can transfer ownership within H2)   

Since the SDR requires an APO we would need to determine how to configure that for non-admin accounts. Ideally, external users wouldn't need to know even that the concept of the APO exists. Hydrus/H2 have always used APOs but those have not been visible to users.

**Comment by justinlittman** [comment]
"Users" for SDR-API are typically service accounts (not people and definitely on tied to sunets). Is this consistent with these requirements?

**Comment by andrewjbtw** [comment]
Two of the known user groups who have been in touch over the past few years about being able to deposit via API:

- a research lab with a lot of data
- a journalism group who would like to integrate depositing with a system where they take in data from outside sources

**Comment by andrewjbtw** [comment]
Whether we do sunet-based authorization or some other strategy seems more like an implementation question.

**Comment by justinlittman** [comment]
It is an implementation question that would be driven by requirements like "Who/what is a user?"

**Comment by peetucket** [comment]
I don't think we want to tie API "users" to SUNets or specific people - the common pattern with APIs is to have an API key that is issued for a specific application, which is in turn managed by a person (who may change over time as the team that manages the application consuming the API has changes in personnel).  This is, for example, how ORCID manages their external -- we register an application, and then a technical contact.  We then get an API key which grants us certain permissions.  In our case, that API key gets the "create" permissions Andrew described above, along with edit/update permissions to anything created by that specific API key.  If needed, you revoke the API key.

**Comment by andrewjbtw** [comment]
That seems reasonable, and to be clear, I wouldn't have expected something other than API keys. My request is for a limit on what someone with those keys can do. I've used a few APIs managed by organizations I don't work for, and I've gone through registration processes for them, and they've all limited what I can do, so this doesn't seem like an unusual request to me.

**Comment by justinlittman** [comment]
Here is my proposal for the simplest possible implementation given the current codebase:

A user can have permissions for 0 or more collections (identified by collection druid). If the user has permissions for 0 collections, then the user can create or update items from any collection and create or update any collection or APO (i.e.,,the current user permissions). Otherwise, if the user has permissions for 1 or more collections, the user can only create or update items in those collections and cannot create or update any collection or APO.

Permissions for a user would be managed via a Rake task (just like how users are currently managed).

**Comment by mjgiarlo** [comment]
@justinlittman What would you think about a @sul-dlss/infrastructure-team + @andrewjbtw discussion this week to talk about design ideas before starting in on this implementation? I'd be happy to get that set up. Implementing something simple and iterating may be the wisest way to start but I'm hesitant to say that's the best option given how little time the team has spent considering how best to satisfy our authorization & access control use cases. Possible questions to delve into could include:

* Is the current authentication scheme in sdr-api sufficient? (With username/password combinations and time-limited tokens for API interactions.)
* How do we make authorization decisions? Where is the data driving these decisions persisted? How do we manage this data?
* How do we manage sdr-api accounts over time? Is a CLI (e.g., `rake`) sufficient for now or should we consider UI tooling?
* Do we need a way (whether in sdr-api or a new service) to mark accounts as active or inactive?
* How do we grant accounts (super-)administrative abilities?
* Whose responsibility is this in SDR? Could/should it live in an existing service (SDR-API, dor-services-app) or is it worthy of a new, dedicated service (per original Cocina design)? Are we inclined in favor of fewer, more monolithic services (e.g., dor-services-app) or microservices (e.g., techmd, suri)?

**Comment by mjgiarlo** [comment]
After reading the thread above again and chatting with @justinlittman a bit, it's justifiable (IMO) to put off any technical design meetings and iterate on J-Litt's proposal.

Unpacking ☝🏻: the ultimate design of authorization within SDR **is worth discussing after** we've had a chance to engage with users of the SDR API (whether directly or via @andrewjbtw). At the moment it does not seem prudent to do a whole lot of legwork without that grounding, lest we implement the wrong thing or rack up a ton of technical debt.

For now, I advocate moving forward with a simple design and implementation that meets the basic needs outlined by @andrewjbtw above, following an agile process: start small and iterate in partnership with users.

I'd like to make a slightly amended proposal based on Justin's that gives us a bit more flexibility without sending us down a 🐰🕳️. How does this sound?

* `sdr-api` authentication stays the same, using username/password credentials to generate tokens for API interactions
* authorization decisions are made within the existing `sdr-api` codebase, not in a new service
* a CLI invoked on the `sdr-api` is sufficient to manage user accounts and permissions
* basing permissions on collections in part by associating 0 or more collection druids with each `sdr-api` account should suffice for all use cases, but I'd like to propose we consider the following:
  * instead of interpreting 0 collection druids as either "access granted to everything" or "no access granted," I might like to add two new fields to the user table (in addition to the collection druids relationship)
  * an `active` flag, which will be on by default but that we can turn off at will to quickly (and possibly temporarily) revoke API access on a per-user basis
  * an `admin` flag clearly allowing a user full access (retaining the current behavior)

So the authorization logic for what @andrewjbtw outlined above would work as follows:

* Create a new collection
  * Disallowed if user is not active
  * Allowed otherwise
* Create a new item
  * Disallowed if user is not active
  * Allowed if user is an admin
  * Disallowed or allowed depending on whether the supplied collection druid is in the list of the user's collection druids
* Update a collection
  * Disallowed if user is not active
  * Allowed if user is an admin
  * Disallowed or allowed depending on whether the collection's druid is in the list of the user's collection druids
* Update an item
  * Disallowed if user is not active
  * Allowed if user is an admin
  * Disallowed or allowed depending on whether the item's collection druid is in the list of the user's collection druids

I'm not sure what to do about the question of ownership that @andrewjbtw raised. That is potentially hairy since Cocina has no notion of this. I'm wondering if ☝🏻 might be good enough to start?

> Since the SDR requires an APO we would need to determine how to configure that for non-admin accounts. Ideally, external users wouldn't need to know even that the concept of the APO exists. Hydrus/H2 have always used APOs but those have not been visible to users.

If an explicit APO druid is not supplied, could we consider defaulting to the APO of the collection?

**Comment by justinlittman** [comment]
Works for me. @mjgiarlo and I discussed calling the flag "priviledged" or "full-access" instead of "admin" (since the apps that would have that auth would not be admins). Since I can't spell "privileged", I will probably go with "full-access".

**Comment by andrewjbtw** [comment]
Works for me too. This looks like it will be enough that we can come back to the groups that expressed interest in an API and start working with them. I don't think there will be a lot of user management tasks (adding/revoking) early on.

For the APO, going with the same APO as the collection being used makes sense as a starting point. It may turn out that there's a use case for depositing items without using a collection at all (as there is internally) but we can handle that in the future.

**Comment by mjgiarlo** [comment]
# Open Questions

* Determine if read-only requests---viewing an item, collection, or APO---should be authorized. And, if so, how. (@andrewjbtw question)

# Tickets to be written up

* Extend `sdr-api` database with new table and two new user fields per design ☝🏻 
* Migrate database in all envs and ensure current accounts get the bits they need (to retain full access)
* Add authorization logic to `sdr-api`, including adding `401` responses to the API spec where applicable
* Add authorization smarts to `sdr-client`
* Support creating collections in `sdr-client`
* Support updating collections in `sdr-client`

**Comment by mjgiarlo** [comment]
# Open Questions

* ~~Determine if read-only requests---viewing an item, collection, or APO---should be authorized. And, if so, how?~~
  * We needn't authorize read-only requests for now, per @andrewjbtw

**Comment by justinlittman** [comment]
I simplified the implementation a notch: Limited access users cannot create collections; however, a limited access user can be configured to add items to an existing collection.

This matches Google Books, the existing known use case for a limited access user.

Of course, this can always be changed in the future as necessary.

**Comment by andrewjbtw** [comment]
That's fine with me. I think it fits with how we handle most external deposits. Few people are allowed to create collections themselves - possibly only staff.

**Comment by mjgiarlo** [comment]
@justinlittman Do you think we can close this issue for now?
