### ISSUE TITLE
Assign "Book (ltr)" process tag to all imported books

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/sdr-api#76]
Use `Process : Content Type : Book (ltr)` for all imported books.

**Comment by andrewjbtw** [comment]
Good question. I think in the long run we'll need to support ltr and rtl deposits via the API but I'm not sure if that's done with the Process tag or some other field (probably the content-type). I'll look into it.

**Comment by andrewjbtw** [comment]
After checking with users who have used these tags in the past, the answer is: 

No, we don't need the process tag. 

This was mainly used by the scanning lab to track RTL vs LTR reading order before those choices were supported in the actual content type. The content type is what determines the actual reading order, not this tag.

**Comment by jcoyne** [comment]
@andrewjbtw are we setting the content type correctly?

**Comment by andrewjbtw** [comment]
I was wrong above. We apparently do need the process tag if we are going to support RTL vs LTR reading order in the future.

Even though the registration form gives you a choice to set the content type for books as ltr or rtl, the only thing this seems to do is auto-generate the process tag for the registered item.

Registration form:

![Screen Shot 2020-01-22 at 11 39 36 AM](https://user-images.githubusercontent.com/8975583/72928051-25205800-3d0c-11ea-8431-788761015d17.png)

Two registered objects in stage as examples of what gets created. I did not create the process tags myself:
https://argo-stage.stanford.edu/catalog?f%5Bproject_tag_ssim%5D%5B%5D=rtl+vs.+ltr

As far as I can tell, the content type in the content metadata is only "book" no matter what the process tag says. Examples of RTL books in prod can be found here:

https://argo.stanford.edu/catalog?f%5Btag_ssim%5D%5B%5D=Process+%3A+Content+Type+%3A+Book+%28rtl%29&page=1&per_page=100

There may be something in the code that distinguishes the two book content types, but I haven't found anything in the datastreams to indicate a difference. It all looks like "book".

So for consistency, I guess we do need the process tag since registration through the API does not auto-generate it. Which means we need to figure out if we can determine the reading order from the Google Books metadata.

**Comment by mjgiarlo** [comment]
Determination of reading direction was moved to sul-dlss/google-books#184.
